[portal]
base_url = "http://localhost:3000"

[tiers]
claimed = ["T1", "T2", "T3", "T4"]
pitch = "Self-hostable hackathon submission + judging platform."

[auth]
organizer   = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..5AJfaYzipRTnqEF-.W08wse_xaFupEnCNmkSzf3EwSR33-a25k4TxWvK2vB62WUpFCsA1A2vAaY2cdxhfnVGaS0h2eYvqjV4LRajIWtxgm3Xg4tyQGENd3bnpu2CquqCwt3EDIEWqGEpKqYGGSf2jaW_NX4VgZoicWV204YXq7mgs2b_KH8N33nnwVVNJCfdTcrrLeoGCa_51OteOw4YWgW9cLBnHaFXx_V-eKZ7R3l_r-xHpkzIkSbVjMQMDM8jiL-ZxkkskDv4N7w3jDa5Q91G9h8RkCK5VyBUYtrIlwPW9Lkl2IZGOYnN6_w.XtBJJ455K16ATvL0j5WePg"
judge_a     = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..gQ3P_bKoOwGm5ZIC.nltrbHkPpB91fm9C_MOJEQyHYJWSzky1JTavRdPd2hbr1-2jQ-_iDF1LnGAeiGfh_LNThWF9EQCZ_dWqVcJbiBvvUBb-zZzLNPTkLPD0wHyn9L0Ky7MeKYVuPU0v0BrO4lwfqRUz1qYYS9JfOwsjLKT1sfw7LXC_vZ2YLIMoNxHtS8-08ve-t0sGHlVjsnuyasrX75Gm6um6SHVamwOR3m1GvDZIYHdDVSYS6vjWN6d7ww4cLweNIEQb3lMs2LAWivtEmqqTI-h_g1s6BeivyAIWJpZeDytz.AbuNUJc3kcj-dgUbm4g8qQ"
judge_b     = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..lCTFQTPO7N2vjhV3.5mY-nNd265GxV-tYPH8V679_8Cq7wtuVgs9jdTfa3AFP-JQ512J7dAJtp9KyPvk04gvLiypaM5UZhh_xEiaEFoMNqrPBC8htQQKanp-WRO4sTWyoAG8AIL58znehMD3cahQuF9T5wspqmZM1Dq54FrhyWP36dVlBJbLYHSB5aATTb9E4UkdPzgcn-5_WpV0dkA2X9-EY15d2nIR8VPw3NbpEf-ssLLLmuv_BDvvv-xCF9xhuZcFKbDD_7z18zzQjujrKXrUdc8cqssxjglKOdLxcS9T-.XPeHXjvS38W-K_ds9mLorg"
participant = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..LSZCjcOjzuOqwpLw.e09KeucOZbhQtJfwK2XCWsyrQjDimtYePQlNElTcz4KYFZNaxZpFWXwFPJsXTmsDnyucEx8b1Tam6V5A_Zfz1PF689dTaf80HlL2J72b3O0X5XMCA4AOyMGZW-wohsoHbwsmbac4HIZE0d8SCHD7ZgpDPLSYQVfYrfjvgFspsjJfzAnmsuaCgq-eY1RsSw_RFTjGtMsdxDQYl-QGwbinmghWxFqCSHvUn5eSKhPVbBxKr72Kx1-B-gOO0AdGC6MnMuBSss2ZBUyr5bzd3yeouCuIkZY-4cqzcKvwnvxfOg.oG7rjDhLfNfA6CSCuAQAQQ"

[routes]
gallery      = "/gallery"
submit       = "/api/submissions"
judge_scores = "/api/judge/scores"
peer_scores  = "/api/judge/scores?judge=cmuj7pkx40002eg9lenp2gkg5"
csv_export   = "/api/events/cmuj7pkxo0007eg9lpm2x619k/export/scores"